language: ruby
rvm:
    - 2.3.3

before_script:
    - chmod +x ./script/cibuild.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
    - bash ./script/cibuild.sh

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
#    - bash ./script/deploy.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN # Set in travis-ci.org dashboard
    local-dir: output
    on:
        branch: gh-pages
